os: linux
sudo: false
language: python
cache: pip

matrix:
  include:
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev"
    - python: "pypy3.5"
  allow_failures:
    - python: "nightly"
  fast_finish: true

services: mongodb

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

before_script:
  - cd Server

script:
  - coverage run --source=app run_test.py

after_success:
  - coverage report
  - coveralls

notifications:
  email: false
